In [18]:
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

In [29]:
dir = "D:\\Machine_Learning\\JumpingChandu\\Dataset\\Train_4"
classes = ['jump','nothing']

def get_data():
    train = []
    for clas in classes:
        path = os.path.join(dir,clas)
        label = classes.index(clas)
        for img in os.listdir(path):
            imgar = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
            imgar = imgar[95:150,0:130]
            train.append([imgar,clas])
    return train


In [30]:
X = []
y = []
train = get_data()
print(train[0][0])
#cv2.imshow("img",train[0][0])
import random
random.shuffle(train)
for img, label in train:
    X.append(img)
    y.append(label)
X = np.array(X).reshape(-1,55,130,1)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [ ]:
cv2.imshow("-",X[0])
cv2.waitKey(0)

In [31]:
np.save("D:\\Machine_Learning\\JumpingChandu\\Dataset\\X7.npy",X)
np.save("D:\\Machine_Learning\\JumpingChandu\\Dataset\\y7.npy",y)

In [26]:
print(X.shape)

(2501, 55, 140, 1)
